### ISSUE TITLE
Add an editor markup for coverage results

### ISSUE THREAD

**Issue by Basile-z** [Basile-z/dexed#189]
~~requires to add more gutter parts, sharing the same gutter for D-Scanner and the debugger is already not super convenient.~~

**Comment by BBasile** [comment]
I may rather use a markup. Support for several icons in the butter [is not well supported for now](http://forum.lazarus.freepascal.org/index.php/topic,38741.0.html), or delay this to the future since a release is needed because of https://github.com/BBasile/Coedit/issues/208
