### ISSUE TITLE
Handle `p *this` in GDB commander

### ISSUE THREAD

**Issue by Basile-z** [Basile-z/dexed#199]
`p *this` is typically used to print the content of an aggregate.

- display the variables in a tree, not just a list.
- at least detect the command to parse it and fill the dedicated GUI element when the result comes.
- at best call it automatically when top level variable list include `this`.

**Comment by BBasile** [comment]
[current work](https://github.com/BBasile/Coedit/tree/recursive-data-list-sucks) shows that the "JSON-ization" of the output produced by the GDBMI is no enough, although in theory we just need to parse the result of the queries in a clever way.

**Comment by BBasile** [comment]
Removed from the upcoming milestone. I need to write a better GDBMI parser.
That's more work than it appears (maybe use Pegged in an external tool ?)
