### ISSUE TITLE
Trailing null issue is back when building with Laz 1.8 + GTK2 widgetset

### ISSUE THREAD

**Issue by Basile-z** [Basile-z/dexed#220]
For now this is only visible in the devel version. It seems that using other widget sets would prevent the issue.

**Comment by BBasile** [comment]
It was #39.

**Comment by BBasile** [comment]
I'll build 3.6.0 for linux with a special compile time definition.

**Comment by Alexey-T** [comment]
ATsynedit has workaround for this bug

**Comment by Basile-z** [comment]
Well nothing to be done here. Just a reminder for me or anyone that would land on this issue: the LCL must be recompiled with `GTK_REMOVE_CLIPBOARD_NULL` as define. I still don't know if Gtk3 is affected as well because dexed crashes directly because of an update loop while realigning.
