### ISSUE TITLE
Out of order messages

### ISSUE THREAD

**Issue by Basile-z** [Basile-z/dexed#336]
Visible for example when using _Run file unittests_ for _Styx_ parser:

![screenshot_20180623_080207](https://user-images.githubusercontent.com/16154339/41806324-1999b6c4-76bc-11e8-9b1d-8cf79ec9b1c0.png)

Possible regression of Lazarus 1.8.4

**Comment by BBasile** [comment]
Fix caused new random problems. TCEProcess is too imbricated with another TAsyncProcess issue, i.e onTerminate event (#337)
