### ISSUE TITLE
options, additionalPATH not hanlded to locate dcd-server and dcd-client

### ISSUE THREAD

**Issue by Basile-z** [Basile-z/dexed#41]
The paths stored in the option _additionalPATH_ are not known by the DCD wrapper. Global options are read after DCD initialization. The other software components that use external processes (custom tools, compilation, symbol list, etc) are not affected.

**Comment by BBasile** [comment]
The basic problem is that the unit `initialization` order of execution is out of control. This is hard to fix.

**Comment by Basile-z** [comment]
I wont change the global architecture and the patterns used for that.
