### ISSUE TITLE
Icons url of the documentation are broken

### ISSUE THREAD

**Issue by Basile-z** [Basile-z/dexed#414]
[Example](https://basile-z.github.io/dexed/widgets_dfmt_commander). Seems to be related to a recent change of pseudo or i didn't noticed previously.

**Comment by redpiller** [comment]
Ahh found the problem:
the link points to:
https://raw.githubusercontent.com/Basile-z/dexed/master/icons/%20other/accept.png
but it should point to:
https://raw.githubusercontent.com/Basile-z/dexed/master/icons/other/accept.png

you need to remove the "%20" thing

**Comment by Basile-z** [comment]
Ha ha. I know that but the problem is that the "%20" is added automatically. after insertion of an inclusion.
This was not the case in the past.

The include : https://github.com/Basile-z/dexed/blob/master/docs/_includes/icurl
How it's used: https://raw.githubusercontent.com/Basile-z/dexed/master/docs/widgets_custom_tools.md

**Comment by redpiller** [comment]
![screenshot_20190129_140257](https://user-images.githubusercontent.com/31500722/51910184-b6494100-23ce-11e9-91a2-8cdfd263e29f.png)

There is a new line character at the end of the include line, the URL formatting then translates it to "%20" which is space bar, you could try to take the last byte out of the file and see what happens

**Comment by Basile-z** [comment]
Thanks for finding this. What has happened with your PR ?

**Comment by redpiller** [comment]
yeah about that... i used the web interface to just remove the '\n' via edit, 
apparently github's internal diff function doesn't detect escape characters as a valid change so effectively i had an empty pull request with +0 and -0 changes, i guess i found a bug within github
