### ISSUE TITLE
In 3.7.4 the Todo list is again cleared when clicking an item

### ISSUE THREAD

**Issue by vporton** [Basile-z/dexed#419]
Regression (#412):

In 3.7.4 the Todo list is again cleared when clicking an item.

Workaround: switch between source tabs.

**Comment by vporton** [comment]
Weird: It sometimes works (the Todo list does not disappears), sometimes doesn't work (the list is cleared).

Not sure what is the criterion of when it works and when doesn't.

**Comment by vporton** [comment]
It seems that the list disappears when clicking an item opens a not open file. When clicking just switches tabs the list does not disappear.

**Comment by vporton** [comment]
Additional small bug: The Todo list blinks when clicking switches tabs.

**Comment by Basile-z** [comment]
I cannot avoid the blink. What happens actually is that the list is cleared and filled again depending on the context. The rule are

- if current file is part of the current project, display the items of the whole project
- if current file is not part of the project, display the items of the current file
- if there is no file but a project, display the items of the current project

```pascal
function TTodoListWidget.getContext: TTodoContext;
begin
  if (fProj = nil) and fDoc.isNil then
    exit(tcNone);
  if (fProj = nil) and fDoc.isNotNil then
    exit(tcFile);
  if (fProj <> nil) and fDoc.isNil then
    exit(tcProject);
  //
  if fProj.isSource(fDoc.fileName) then
    exit(tcProject)
  else
    exit(tcFile);
end; 
```

**Comment by Basile-z** [comment]
I wont release again before more changed and fixes are pushed. This regression is not a big problem. The big problem was when the position in the document was not restored.
