### ISSUE TITLE
Paste action works differently than Ctrl+V

### ISSUE THREAD

**Issue by vporton** [Basile-z/dexed#425]
I assigned "Paste" action to Shift+Ins shortcut.

When the last char of the pasted text is \n, Shift+Ins (unlike Ctrl+V) fails to insert this \n.

This is very inconvenient. Please make Paste to behave the same way as Ctrl+V.

Dexed 3.7.4.

**Comment by Basile-z** [comment]
> When the last char of the pasted text is \n

there is no \n at the end.

**Comment by vporton** [comment]
Why have you closed the bug? If you won't fix, make WONTFIX, not INVALID.

It _is_ a bug after all.
