### ISSUE TITLE
Automatically make identifiers camelCase

### ISSUE THREAD

**Issue by vporton** [Basile-z/dexed#429]
I want an extension which would automatically make all identifiers (in the current document or in the entire project, dependently on a user option) camelCase.

- `xx_yy` -> `xxYy`
- `XX_YY` -> `XxYy`

Not sure what to do for `x_Y`.

It also should update all project files that depend on the current file.

**Comment by Basile-z** [comment]
That would probably also affect the types if done in the IDE.
