### ISSUE TITLE
Auto-indent regression

### ISSUE THREAD

**Issue by Basile-z** [Basile-z/dexed#431]
```d
private enum pseudoTokenHandlers = [
    //"q{", "lexTokenString",
]; // type ENTER after the pipe |         
```

Can you take a look @mleise ? This must be caused by the stuff you added on Monday.

**Comment by mleise** [comment]
I was away from GitHub for a few days. Sorry for the regression. I'll later have a look at what caused it and review the fix. Apparently the brace in the comment was interpreted as start of a block and the new-line "correctly" indented based on that.
From a glance, in https://github.com/Basile-z/dexed/commit/1dc0dab22bc824870e2cdc628bae67f3612d1fa0#diff-5be5f8df9ca21d3cf9ece2b920e7f28fL1732 I was calculating the indentation level based on the next line, knowing that it was a change from how it worked before, but I can't remember the rationale and it looks like I didn't leave any comments either...

**Comment by Basile-z** [comment]
I have fixed it anyway using another strategy, see https://github.com/Basile-z/dexed/commit/b140ac1c848a157763cac36f361dc0f4dd7fdcba and https://github.com/Basile-z/dexed/commit/7d372c1eba901a669f6ac6bb3e9f15dc87b8ce83, which works fine so far.
