### ISSUE TITLE
Go to line number

### ISSUE THREAD

**Issue by vporton** [Basile-z/dexed#432]
It seems that there is no "go to line number..." menu item and/or key.

Please add it.

**Comment by Basile-z** [comment]
![gtl](https://user-images.githubusercontent.com/16154339/52106819-53d18a00-25f4-11e9-9000-8ede7ab4aaf4.png)

**Comment by vporton** [comment]
It is missing the ability to bind a key to this operation.

**Comment by vporton** [comment]
When I type "goto" in the "(filter)" field,I see no "GotoLine". It is a bug.

**Comment by Basile-z** [comment]
No the filter is only used to retrieve the shortcuts value, e.g CTRL+W not the name of the action it's attached to.
