### ISSUE TITLE
Project output kind not always correctly interpreted from the DUB JSON

### ISSUE THREAD

**Issue by vporton** [Basile-z/dexed#434]
[This project](https://github.com/vporton/shlex-dlang/tree/742adfdb9f6469c46ae8e65d9b2850f27d0f9566) cannot be debugged.

Dexed says "The project cannot be debugged because it does not output an executable" despite I set "unittest - application" configuration and created file `test.d` with `main()` and added that one to the project.

It seems to be a Dexed 3.7.4 bug.

**Comment by Basile-z** [comment]
If you remove the global `targetType` it works:

```diff
{
  "name" : "shlex",
  "description" : "Simple shell-like lexical analysis library",
  "homepage" : "https://github.com/vporton/shlex-dlang",
  "license" : "GPL-3.0 or later",
  "authors" : [
    "Victor Porton"
  ],
-  "targetType" : "library",
  "configurations": [
    {
      "name": "application",
      "targetType": "executable",
      "sourceFiles": [
        "test.d"
      ]
    },
    {
      "name": "shared-library",
      "targetType": "dynamicLibrary"
    },
    {
      "name": "static-library",
      "targetType": "staticLibrary"
    }
  ]
}
```

It's only a workaround.
