### ISSUE TITLE
Trouble assigning a shorcut key

### ISSUE THREAD

**Issue by vporton** [Basile-z/dexed#435]
When assigning Ctrl+G for GotoLine, I got:

> warning, "Ctrl+G" is already assigned in the "Edit" category and it is not guaranteed to work properly

There is no easy enough way to understand where it was assigned and unassign.

**Comment by Basile-z** [comment]
Use the filter to find where it's asssigned

**Comment by vporton** [comment]
Thanks.

But it is counter-intuitive that the filter works be key name and not by operation name.

It should accept both (key name or operation name), probably.
