### ISSUE TITLE
Expressions in debugger are not evaluated

### ISSUE THREAD

**Issue by vporton** [Basile-z/dexed#437]
When in Dexed 3.7.4 I select in the debugger of a running program "Evaluate custom expression", click the Evaluate button, and enter an expression, nothing happens. Particularly the value is not printed in the message window.

The same (nothing) happens when I select "Evaluate selected variable", select a variable in the variable list and click the Evaluate button.

A side note: some variables (consider `this` in a complex OO program) may be rather long. Maybe printing them in the message window is wrong and instead a new window with the value of the variable should be opened.

**Comment by Basile-z** [comment]
It's a GDB thing.

**Comment by vporton** [comment]
Then you should recommend which version of GDB to use.

Moreover, Dexed should check that the version is correct and message the user if not.

**Comment by vporton** [comment]
It is stable Ubuntu 18.10.

If it does not work, we need to submit a bug report to Ubuntu. Please tell me what to write in the report.
