### ISSUE TITLE
CPU subwindow of the debugger should be removable

### ISSUE THREAD

**Issue by vporton** [Basile-z/dexed#440]
CPU subwindow of the debugger should be removable, because most people may need it (if any) only in the case of a compiler bug.

Showing it by default may be a mistake.

**Comment by Basile-z** [comment]
>  only in the case of a compiler bug.

That's not true. It's pretty much the only way to modify a variable. Each field of the CPU inspector is modified in the program that's debugged. E.g edit RAX, type ENTER, for the program now RAX has ne value.

**Comment by Basile-z** [comment]
Well it's more about tabs considering how the UI is done. Maybe the tab index should be saved an restored, so that the CPU inspector is not the default view.
