### ISSUE TITLE
IDE froze right on start up

### ISSUE THREAD

**Issue by MassMessage** [Basile-z/dexed#451]
Hey guys, I downloaded Dexed yesterday and it was working beutifully for hours, then I need to close it and when I reopened, the IDE stooped working; it frozes right on the start up.
Any idea what could possibility be? I haven't much experience on linux and I haven't used it for a while until yesterday. I tried to clear cache or something but I'm unsure how do with Dexed.
I've also tried several resinstalls... no luck.

Info:

Dexed: 3.7.8
OS: Ubuntu 18.04.2 LTS

**Comment by Basile-z** [comment]
the bug is known. It's related to docking. delete the the `docking.xml` file in your `.config/dexed` folder, and it should start again.

**Comment by Basile-z** [comment]
Have you find some time to do what i suggested yesterday ?

**Comment by MassMessage** [comment]
I'm sorry, I haven't done that. I ended up installing a previous version, which is working fine for the past couple of days. If it's a know issue, I guess that one can be closed...
