### ISSUE TITLE
Building issues: Broken dependency: DexedDesignControls

### ISSUE THREAD

**Issue by The-BigDaddy** [Basile-z/dexed#456]
Lazarus version: 2.0.0

DMD version: 2.085.0

Dub version: 1.13.0

So the skinny is I cloned `master`, `cd lazproj`, `lazbuild -B dexed.lpi`, and

```
Error: (lazbuild) Broken dependency: DexedDesignControls
```

Don't know if it's related to what I found when just testing if Lazarus worked fine by compiling a project:

```
Compile Project, Target: /home/bigdaddy/tmp/project1: Success, Warnings: 2
project1.lpr(21,1) Warning: "crtbeginS.o" not found, this will probably cause a linking failure
project1.lpr(21,1) Warning: "crtendS.o" not found, this will probably cause a linking failure
```

But I have a feeling it's not related to that.

**Comment by Basile-z** [comment]
The building  instructions are probably incomplete. Gotta uninstall from Lazarus and see how this can be done from command line and from scratch.

**Comment by Basile-z** [comment]
It works for me after uninstalling the said "broken" package from the Lazarus IDE. 
Try `lazbuild -B -r dexed.lpi > log.txt` and share the full log if this still does not work.
Other option is to install the package in Lazarus and after rebuilding Lazarus, open dexed.lpi and compile it from the Laz.

**Comment by Basile-z** [comment]
See http://wiki.freepascal.org/Install_IDE_packages_without_the_IDE#Compile_and_register_the_required_packages too. Apply the method to the file `dexeddesigncontrols.lpk`

**Comment by Basile-z** [comment]
Is this okay now ?
