### ISSUE TITLE
DUB build error since version 3.7.6

### ISSUE THREAD

**Issue by Sadoon-AlBader** [Basile-z/dexed#472]
Whenever compiling a project using DUB in versions 3.7.6 or higher I get this error. Using the command line to execute the same commands works fine. Versions 3.7.5 and lower work just fine.

compiling /home/user/Documents/D/gtkdtest/dub.json
/home/user/Documents/D/gtkdtest/dub.json has not been successfully compiled
error: DUB has returned the status 127 (Program-defined exit status)
Build duration: 0 minutes, 0 seconds and 59 msecs

**Comment by Basile-z** [comment]
Can you show me the text displayed after the action "Project/View project command line" ?
Also I'd like to see the project JSON.

**Comment by Sadoon-AlBader** [comment]
Never mind, I found the solution.
Basically, it seems to only happen when you start dexed in a folder you don't have write access to. My xfce desktop shortcut used to start it inside /usr/bin. I just fixed it by making it start in my home directory, or just leaving the box empty does that anyways. Thank you :)

**Comment by Basile-z** [comment]
Thnaks, I think i'll remove the special support for sudo in the installer. In the past there's been other related problems related.

**Comment by Sadoon-AlBader** [comment]
> Thnaks, I think i'll remove the special support for sudo in the installer. In the past there's been other related problems reported.

Nooo I think it's better to have sudo support so that we can install it for all users. it works well, as long as the desktop shortcut isn't made by an idiot like me xD
