### ISSUE TITLE
Horizontal scrolling is missing in the Variables view

### ISSUE THREAD

**Issue by vporton** [Basile-z/dexed#477]
Horizontal scrolling is missing in the Variables view:
![Screenshot from 2019-06-11 05-30-34](https://user-images.githubusercontent.com/2900574/59239440-292eb800-8c0a-11e9-89ec-ff5d626955c2.png)

Moreover, it should be added a mean to view the value (such as in a separate dialog or at least popup) a variable whose value is long (like `this` in screenshot).

**Comment by Basile-z** [comment]
This is also related to the fact that the variable are not displayed in a tree... But as  explained a few months ago I've a bit given up with this widget.

**Comment by Basile-z** [comment]
I see this the problem. In a first time it appears but after resizing it's never displayed anymore. Maybe a LCL bug then.
